# Generated by Django 5.2.17 on 2026-09-28 06:19

import delivery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("tutorial", "Tutorial"),
                            ("lab", "Lab / Practical"),
                        ],
                        default="lecture",
                        max_length=10,
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=60)),
                (
                    "batch",
                    models.CharField(
                        blank=True, help_text="Lab batch, e.g. B1", max_length=30
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("tutorial", "Tutorial"),
                            ("lab", "Lab / Practical"),
                        ],
                        default="lecture",
                        max_length=10,
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=60)),
                (
                    "is_extra",
                    models.BooleanField(
                        default=False,
                        help_text="Added manually (not generated from the timetable)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "coverage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full", "Fully covered"),
                            ("partial", "Partially covered"),
                            ("different", "Covered something else"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "actual_topics",
                    models.TextField(
                        blank=True, verbose_name="What was actually covered"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Class notes")),
                ("notes_file", models.FileField(blank=True, upload_to="class_notes/")),
                (
                    "resource_link",
                    models.URLField(blank=True, verbose_name="Slides / recording link"),
                ),
                (
                    "notes_shared",
                    models.BooleanField(
                        default=True, verbose_name="Share notes with students"
                    ),
                ),
                (
                    "checkin_code",
                    models.CharField(
                        default=delivery.models.generate_checkin_code, max_length=6
                    ),
                ),
                ("checkin_open", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "plan_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="courses.planitem",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="delivery.timetableslot",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("A", "Absent"),
                            ("L", "Late"),
                            ("E", "Excused / OD"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("self_checked_in", models.BooleanField(default=False)),
                ("marked_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="delivery.classsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "student")},
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("course", "date")},
            },
        ),
    ]
