# Generated by Django 5.2.17 on 2026-09-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_academicterm_planitem_planned_date_course_term"),
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="classsession",
            name="plan_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Plan item chosen by hand; timetable sync keeps it",
            ),
        ),
        migrations.CreateModel(
            name="SupplementaryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "follows_weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Follow the timetable of",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="e.g. compensation for the 15 Aug holiday",
                        max_length=120,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplementary_days",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("course", "date")},
            },
        ),
    ]
