# Generated by Django 5.2.17 on 2026-09-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="prn",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="PRN / university number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roll_no",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Roll number"
            ),
        ),
    ]
