# Generated by Django 5.2.17 on 2026-09-28 06:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ISE", "In-semester evaluation (continuous)"),
                            ("MSE", "Mid-semester exam"),
                            ("ESE", "End-semester exam"),
                            ("TW", "Term work / lab"),
                            ("ORAL", "Oral / practical exam"),
                        ],
                        default="ISE",
                        max_length=5,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Weight (% of final)",
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20"),
                        max_digits=6,
                        verbose_name="Reported out of",
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("average", "Average of items"),
                            ("sum", "Sum of items"),
                            ("best", "Best N items"),
                        ],
                        default="average",
                        max_length=10,
                    ),
                ),
                (
                    "best_of",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Used when aggregation is 'Best N'"
                    ),
                ),
                (
                    "min_pass_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Minimum % needed in this component to pass",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField(blank=True, null=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20"), max_digits=6
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="1. All questions are compulsory unless stated otherwise.\n2. Figures to the right indicate full marks.\n3. Assume suitable data wherever necessary.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Scheduled"),
                            ("marked", "Marks released"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="exams.assessmentcomponent",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                    ),
                ),
                ("units", models.ManyToManyField(blank=True, to="courses.unit")),
            ],
            options={
                "ordering": ["date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5"), max_digits=5
                    ),
                ),
                (
                    "bloom_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "L1 Remember"),
                            (2, "L2 Understand"),
                            (3, "L3 Apply"),
                            (4, "L4 Analyze"),
                            (5, "L5 Evaluate"),
                            (6, "L6 Create"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("short", "Short answer"),
                            ("long", "Descriptive"),
                            ("numerical", "Numerical"),
                            ("mcq", "MCQ"),
                            ("design", "Design / open-ended"),
                        ],
                        default="long",
                        max_length=10,
                    ),
                ),
                ("answer_key", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Teacher"),
                            ("generated", "Generated from syllabus"),
                            ("ai", "AI assisted"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.course",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.courseoutcome",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.topic",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="courses.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["unit__number", "marks", "bloom_level", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=40)),
                ("label", models.CharField(max_length=10)),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper",
                        to="exams.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.question"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ExamAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absentees",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="ExamMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks_obtained",
                        to="exams.examquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("exam_question", "student")},
            },
        ),
    ]
