# Generated by Django 5.2.17 on 2026-09-28 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
        ("courses", "0002_academicterm_planitem_planned_date_course_term"),
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="candidates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students registered for this re-exam / additional assessment",
                related_name="retake_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="policy",
            field=models.CharField(
                choices=[
                    ("replace", "Replaces the original score"),
                    ("best", "Better of original and new score"),
                ],
                default="replace",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("regular", "Regular assessment"),
                    ("reexam", "Re-exam (for failed / absent students)"),
                    ("additional", "Additional / make-up assessment"),
                ],
                default="regular",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="replaces_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="The assignment this make-up stands in for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retakes",
                to="classroom.assignment",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="replaces_exam",
            field=models.ForeignKey(
                blank=True,
                help_text="The exam this re-exam / make-up stands in for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retakes",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g. the re-exam term it is conducted in",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.academicterm",
            ),
        ),
    ]
