# Generated by Django 5.2.17 on 2026-09-28 06:19

import courses.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=120)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "First year"),
                            (2, "Second year"),
                            (3, "Third year"),
                            (4, "Final year"),
                        ],
                        default=1,
                    ),
                ),
                ("semester", models.PositiveSmallIntegerField(default=1)),
                (
                    "division",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Division / section"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True, help_text="e.g. 2026-27", max_length=20
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("3"), max_digits=4
                    ),
                ),
                (
                    "lecture_hours",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Lecture hrs/week"
                    ),
                ),
                (
                    "tutorial_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tutorial hrs/week"
                    ),
                ),
                (
                    "practical_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Practical hrs/week"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("prerequisites", models.TextField(blank=True)),
                ("syllabus_file", models.FileField(blank=True, upload_to="syllabi/")),
                ("syllabus_text", models.TextField(blank=True)),
                (
                    "join_code",
                    models.CharField(
                        default=courses.models.generate_join_code,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "co_teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses_co_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField()),
                (
                    "bloom_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "L1 Remember"),
                            (2, "L2 Understand"),
                            (3, "L3 Apply"),
                            (4, "L4 Analyze"),
                            (5, "L5 Evaluate"),
                            (6, "L6 Create"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "target_percent",
                    models.PositiveSmallIntegerField(
                        default=60, help_text="Score a student needs to attain this CO"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("textbook", "Textbook"),
                            ("reference", "Reference book"),
                            ("online", "Online resource"),
                        ],
                        default="textbook",
                        max_length=12,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("lab", "Lab / practical"),
                            ("project", "Project"),
                            ("presentation", "Presentation / seminar"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_template",
                    models.BooleanField(
                        default=True, help_text="Shown in the course rubric library"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubrics",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_template", "title"],
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "max_points",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5"), max_digits=6
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="criteria",
                        to="courses.courseoutcome",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="courses.rubric",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="RubricLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=60)),
                ("points", models.DecimalField(decimal_places=2, max_digits=6)),
                ("descriptor", models.TextField(blank=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="courses.rubriccriterion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-points"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=250)),
                ("hours", models.PositiveSmallIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="courses.course",
                    ),
                ),
                (
                    "outcomes",
                    models.ManyToManyField(
                        blank=True, related_name="units", to="courses.courseoutcome"
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="courses.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("tutorial", "Tutorial"),
                            ("lab", "Lab / Practical"),
                        ],
                        default="lecture",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                (
                    "objective",
                    models.TextField(blank=True, verbose_name="Learning objective"),
                ),
                (
                    "bloom_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "L1 Remember"),
                            (2, "L2 Understand"),
                            (3, "L3 Apply"),
                            (4, "L4 Analyze"),
                            (5, "L5 Evaluate"),
                            (6, "L6 Create"),
                        ],
                        default=2,
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                ("pedagogy", models.CharField(blank=True, max_length=200)),
                ("tools", models.TextField(blank=True, verbose_name="Digital tools")),
                (
                    "pre_class",
                    models.TextField(blank=True, verbose_name="Before class"),
                ),
                ("in_class", models.TextField(blank=True, verbose_name="In class")),
                (
                    "post_class",
                    models.TextField(blank=True, verbose_name="After class"),
                ),
                ("resources", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="courses.course",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.experiment",
                    ),
                ),
                (
                    "outcomes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="plan_items",
                        to="courses.courseoutcome",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="plan_items", to="courses.topic"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_items",
                        to="courses.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "student")},
            },
        ),
    ]
