# Generated by Django 5.2.17 on 2026-09-28 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Even Term 2026", max_length=120),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("odd", "Odd term"),
                            ("even", "Even term"),
                            ("reexam", "Re-exam"),
                            ("special", "Special exam"),
                        ],
                        default="odd",
                        max_length=10,
                    ),
                ),
                (
                    "academic_year",
                    models.PositiveSmallIntegerField(help_text="e.g. 2026"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="The current term everyone lands in"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-academic_year", "-start_date", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="planitem",
            name="planned_date",
            field=models.DateField(
                blank=True,
                help_text="From an imported lesson plan; the synced timetable date is used when present",
                null=True,
                verbose_name="Proposed date",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.academicterm",
            ),
        ),
    ]
