# Generated by Django 5.2.17 on 2026-09-28 06:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("instructions", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("lab", "Lab write-up / journal"),
                            ("quiz", "Quiz / class test"),
                            ("project", "Mini project"),
                            ("presentation", "Presentation / seminar"),
                            ("activity", "Activity"),
                        ],
                        default="assignment",
                        max_length=15,
                    ),
                ),
                (
                    "max_points",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10"), max_digits=6
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("attachment", models.FileField(blank=True, upload_to="assignments/")),
                ("reference_link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which ISE / term-work bucket this counts toward",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="exams.assessmentcomponent",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                    ),
                ),
                (
                    "outcomes",
                    models.ManyToManyField(blank=True, to="courses.courseoutcome"),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="courses.rubric",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Answer / notes")),
                ("file", models.FileField(blank=True, upload_to="submissions/")),
                (
                    "link",
                    models.URLField(
                        blank=True, verbose_name="Link (GitHub, Colab, Drive...)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("turned_in", "Turned in"),
                            ("returned", "Graded & returned"),
                        ],
                        default="assigned",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score_source",
                    models.CharField(
                        blank=True,
                        help_text="'rubric' when computed from criteria, 'total' when entered directly",
                        max_length=10,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="classroom.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.CreateModel(
            name="CriterionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=6)),
                ("comment", models.CharField(blank=True, max_length=300)),
                (
                    "derived",
                    models.BooleanField(
                        default=False,
                        help_text="Distributed from a total score, not picked directly",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.rubriccriterion",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.rubriclevel",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="classroom.submission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "criterion")},
            },
        ),
    ]
